carcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='index'),
    path('cars/<int:car_id>/', views.cars_detail, name='detail'),
    path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
    path('cars/<int:car_id>/add_cleaning/', views.add_cleaning, name='add_cleaning')
]

main_app/models.py
from django.db import models
from django.urls import reverse

CLEANING = (
    ('M', 'Morning'), 
    ('MD', "Mid-Day"), 
    ('N', 'Night')
)

class Car(models.Model):
    name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    bodystyle = models.CharField(max_length=100)

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse('detail', kwargs={'car_id': self.id})

class Cleaning(models.Model):
    date = models.DateField()
    cleantime = models.CharField(max_length=100, choices=CLEANING, default=None)

cat = models.ForeignKey(
    Car,
    on_delete=models.CASCADE
)

def __str__(self):
    return f"{self.get_cleantime_display()} on {self.date}"

class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Cleaning

class CleaningForm(ModelForm):
    class Meta:
        model = Cleaning
        fields = ['date', 'cleantime']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Car
from .forms import CleaningForm
from django.http import HttpResponse

class CarUpdate(UpdateView):
    model = Car
    fields = ['color']

class CarDelete(DeleteView):
    model = Car
    success_url = '/cars/'


class CarCreate(CreateView):
    model = Car
    fields= '__all__'
    success_url = '/cars/'


def home(request):
    return HttpResponse('<h1>hello</h1>')

def about(request):
    return render(request, 'about.html')

def cars_index(request):
    cars = Car.objects.all()
    return render(request, 'cars/index.html', { 'cars': cars })

def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    cleaning_form = CleaningForm()
    return render(request, 'cars/detail.html', {'car': car, 'cleaning_form': cleaning_form})

def add_cleaning(request, car_id):
    form = CleaningForm(request.POST)
    if form.is_valid():
        new_cleaning = form.save(commit=False)
        new_cleaning.car_id = car_id
        new_cleaning.save()
        return redirect('detail', car_id=car_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Car Collector</h1>
<hr />

{% endblock %}

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;CarCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'cars_create' %}">Add a Car</a></li>
          <li><a href="{% url 'index' %}">View All My Cars</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Car Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Car Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ car.manufacturer }} {{ car.name }}</span>
        <p>Color: {{ car.color }}</p>
        <p>Bodystyle: {{ car.bodystyle }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cars_update' car.id %}">Edit</a>
        <a href="{% url 'cars_delete' car.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_cleaning' car.id %}" method="POST">
      {% csrf_token %}
      {{ cleaning_form.as_p }}
      <input type="submit" class="btn" value="Add Cleaning">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Cleaning</th></tr>
      </thead>
      <tbody>
        {% for cleaning in car.cleaning_set.all %}
          <tr>
            <td>{{cleaning.date}}</td>
            <td>{{cleaning.get_cleantime_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Car List</h1>

{% for car in cars %}
  <div class="card">
    <a href="{% url 'detail' car.id %}">
    <div class="card-content">
      <span class="card-title">{{ car.name }}</span>
      <p>Manufacturer: {{ car.manufacturer }}</p>
      <p>Color: {{ car.color }}</p>
      <p>Bodystyle: {{ car.bodystyle }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.manufacturer }} {{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.manufacturer}} {{object.name}}</span></h1>
{% else %}
<h1>Add Car</h1>
{% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Add Car!" class="btn">
  </form>
{% endblock %}